### ISSUE TITLE
Stuck in update data

### ISSUE THREAD

**Issue by MichelBrossard** [corvideon/InstantWP#83]
Hi,

Usually, Seamus Bradly helps me out. Since he's no longer an InstantWP owner, he suggested to open an issue at the GitHub page.
I try to duplicate my Web site on my local server with InstantWP 5.3.6. I'm blocked in step 3 (Update data) with a blank URL and no button next.
I note the dup-installor-log.txt end by INSTALLER ERROR:
*** PHP Fatal Error Message: Uncaught Error: Call to undefined function token_get_all() in /var/www/localhost/htdocs/wordpress/dup-installer/classes/config/class.wp.config.tranformer.php:307
Stack trace:
#0 /var/www/localhost/htdocs/wordpress/dup-installer/classes/config/class.wp.config.tranformer.php(72): WPConfigTransformer->parse_wp_config('
Hope you can help me.
With kind regards,
Michel Caron
Brossard, Canada

**Comment by migube** [comment]
I got INSTALL ERROR!
[PHP ERR][FATAL] MSG:Uncaught Error: Call to undefined function token_get_all() in /var/www/localhost/htdocs/wordpress/dup-installer/lib/config/class.wp.config.tranformer.php:387 Stack trace: #0 /var/www/localhost/htdocs/wordpress/dup-installer/lib/config/class.wp.config.tranformer.php(78): WPConfigTransformer->parse_wp_config('exists('constant', 'WP_CONTENT_DIR') #2 /var/www/localhost/htdocs/wordpress/dup-installer/classes/config/class.boot.php(75): DUPX_InstallerState::getInstance(false) #3 /var/www/localhost/htdocs/wordpress/dup-installer/main.installer.php(37): DUPX_Boot::init() #4 {main} thrown [CODE:1|FILE:/var/www/localhost/htdocs/wordpress/dup-installer/lib/config/class.wp.config.tranformer.php|LINE:387]
