### ISSUE TITLE
Use of WMPL

### ISSUE THREAD

**Issue by jmartinez1969** [corvideon/InstantWP#84]
I am want to test the wpml plug in (https://wpml.org/) but once activated, one cannot access/see the admin dashboard, giving a Server HTTP 500 error. 

I tried restarting but no way to access the admin dashboard.

![wpml after activation](https://user-images.githubusercontent.com/48023779/53425701-e3801380-39bb-11e9-9d04-72dd54067a01.jpg)
![wpml plugin before activation](https://user-images.githubusercontent.com/48023779/53425702-e3801380-39bb-11e9-9ed0-4d7ec01b6c41.jpg)

**Comment by bitos2002** [comment]
Hello,
I have the same problem with VisualComposer.
My debug log information is the following:
-----
Fatal error: Uncaught Error: Call to undefined function VisualComposer\Framework\token_get_all() in /var/www/localhost/htdocs/wordpress/wp-content/plugins/visualcomposer/visualcomposer/Framework/Autoload.php:137 Stack trace: #0 /var/www/localhost/htdocs/wordpress/wp-content/plugins/visualcomposer/visualcomposer/Modules/Autoload/ElementsAutoload.php(96): VisualComposer\Framework\Autoload->tokenizeComponents(Array) #1 /var/www/localhost/htdocs/wordpress/wp-content/plugins/visualcomposer/visualcomposer/Modules/Autoload/ElementsAutoload.php(57): VisualComposer\Modules\Autoload\ElementsAutoload->getSingleComponent(Array) #2 /var/www/localhost/htdocs/wordpress/wp-content/plugins/visualcomposer/visualcomposer/Modules/Autoload/ElementsAutoload.php(29): VisualComposer\Modules\Autoload\ElementsAutoload->getComponents() #3 [internal function]: VisualComposer\Modules\Autoload\ElementsAutoload->VisualComposer\Modules\Autoload\{closure}('', 'init') #4 /var/www/localhost/htdocs/wordpress/wp-content/plugins/visualcomposer/visualcomposer/ in /var/www/localhost/htdocs/wordpress/wp-content/plugins/visualcomposer/visualcomposer/Framework/Autoload.php on line 137
-----
Any one can help me?
Thanks !!!
Oscar
